export type SupportedLanguage = "ru" | "en";

export type BookDefinition = {
  id: string;
  canonicalBook: string;
  chapters: number;
  names: Record<SupportedLanguage, string>;
  aliases: Record<SupportedLanguage, string[]>;
  fallbackChapterOnVerse?: number;
};

const book = (
  id: string,
  canonicalBook: string,
  chapters: number,
  ruName: string,
  ruAliases: string[],
  enAliases: string[],
  fallbackChapterOnVerse?: number,
): BookDefinition => ({
  id,
  canonicalBook,
  chapters,
  names: { ru: ruName, en: canonicalBook },
  aliases: { ru: ruAliases, en: enAliases },
  fallbackChapterOnVerse,
});

export const BOOKS: BookDefinition[] = [
  book("genesis", "Genesis", 50, "Бытие", ["книга бытие", "бытие", "бытия", "бте"], ["book of genesis", "genesis", "gen"]),
  book("exodus", "Exodus", 40, "Исход", ["книга исход", "исход"], ["book of exodus", "exodus", "exod"]),
  book("leviticus", "Leviticus", 27, "Левит", ["книга левит", "левита", "левит"], ["leviticus", "lev"]),
  book("numbers", "Numbers", 36, "Числа", ["книга чисел", "чисел", "числа"], ["book of numbers", "numbers", "num"]),
  book("deuteronomy", "Deuteronomy", 34, "Второзаконие", ["второзакония", "второзаконие"], ["deuteronomy", "deut"]),
  book("joshua", "Joshua", 24, "Иисус Навин", ["книга иисуса навина", "иисуса навина", "иисус навин", "навина"], ["book of joshua", "joshua", "josh"]),
  book("judges", "Judges", 21, "Судьи", ["книга судей", "судей", "судьи"], ["book of judges", "judges", "judg"]),
  book("ruth", "Ruth", 4, "Руфь", ["книга руфь", "руфи", "руфь"], ["book of ruth", "ruth"]),
  book("1-samuel", "1 Samuel", 31, "1 Царств", ["первая книга царств", "первое царств", "первая царств", "1 царств"], ["first samuel", "1st samuel", "1 samuel"]),
  book("2-samuel", "2 Samuel", 24, "2 Царств", ["вторая книга царств", "второе царств", "вторая царств", "2 царств"], ["second samuel", "2nd samuel", "2 samuel"]),
  book("1-kings", "1 Kings", 22, "3 Царств", ["третья книга царств", "третье царств", "третья царств", "3 царств"], ["first kings", "1st kings", "1 kings"]),
  book("2-kings", "2 Kings", 25, "4 Царств", ["четвертая книга царств", "четвертое царств", "четвертая царств", "4 царств"], ["second kings", "2nd kings", "2 kings"]),
  book("1-chronicles", "1 Chronicles", 29, "1 Паралипоменон", ["первая паралипоменон", "первое паралипоменон", "1 паралипоменон"], ["first chronicles", "1st chronicles", "1 chronicles"]),
  book("2-chronicles", "2 Chronicles", 36, "2 Паралипоменон", ["вторая паралипоменон", "второе паралипоменон", "2 паралипоменон"], ["second chronicles", "2nd chronicles", "2 chronicles"]),
  book("ezra", "Ezra", 10, "Ездра", ["книга ездры", "ездры", "ездра"], ["book of ezra", "ezra"]),
  book("nehemiah", "Nehemiah", 13, "Неемия", ["книга неемии", "неемии", "неемия"], ["book of nehemiah", "nehemiah", "neh"]),
  book("esther", "Esther", 10, "Есфирь", ["книга есфирь", "есфири", "есфирь"], ["book of esther", "esther", "est"]),
  book("job", "Job", 42, "Иов", ["книга иова", "иова", "иов"], ["book of job", "job"]),
  book("psalms", "Psalms", 150, "Псалом", ["книга псалмов", "псалтирь", "псалтырь", "псалмах", "псалмов", "псалмы", "псалом", "псалма", "псалме"], ["book of psalms", "the psalms", "psalms", "psalm"]),
  book("proverbs", "Proverbs", 31, "Притчи", ["книга притчей", "притчей", "притчи"], ["book of proverbs", "proverbs", "prov"]),
  book("ecclesiastes", "Ecclesiastes", 12, "Екклесиаст", ["екклесиаста", "екклесиаст", "экклезиаст"], ["ecclesiastes", "eccles"]),
  book("song", "Song of Solomon", 8, "Песнь Песней", ["песня песней", "песни песней", "песнь песней"], ["song of solomon", "song of songs", "songs"]),
  book("isaiah", "Isaiah", 66, "Исаия", ["книга исаии", "исаии", "исайя", "исаия"], ["book of isaiah", "isaiah", "isa"]),
  book("jeremiah", "Jeremiah", 52, "Иеремия", ["книга иеремии", "иеремии", "иеремия"], ["book of jeremiah", "jeremiah", "jer"]),
  book("lamentations", "Lamentations", 5, "Плач Иеремии", ["книга плач иеремии", "плач иеремии"], ["lamentations of jeremiah", "lamentations", "lam"]),
  book("ezekiel", "Ezekiel", 48, "Иезекииль", ["книга иезекииля", "иезекииля", "иезекииль"], ["book of ezekiel", "ezekiel", "ezek"]),
  book("daniel", "Daniel", 12, "Даниил", ["книга даниила", "даниила", "даниил"], ["book of daniel", "daniel", "dan"]),
  book("hosea", "Hosea", 14, "Осия", ["книга осии", "осии", "осия"], ["book of hosea", "hosea", "hos"]),
  book("joel", "Joel", 3, "Иоиль", ["книга иоиля", "иоиля", "иоиль"], ["book of joel", "joel"]),
  book("amos", "Amos", 9, "Амос", ["книга амоса", "амоса", "амос"], ["book of amos", "amos"]),
  book("obadiah", "Obadiah", 1, "Авдий", ["книга авдия", "авдия", "авдий"], ["book of obadiah", "obadiah", "obad"], 1),
  book("jonah", "Jonah", 4, "Иона", ["книга ионы", "ионы", "иона"], ["book of jonah", "jonah"]),
  book("micah", "Micah", 7, "Михей", ["книга михея", "михея", "михей"], ["book of micah", "micah"]),
  book("nahum", "Nahum", 3, "Наум", ["книга наума", "наума", "наум"], ["book of nahum", "nahum"]),
  book("habakkuk", "Habakkuk", 3, "Аввакум", ["книга аввакума", "аввакума", "аввакум"], ["book of habakkuk", "habakkuk", "hab"]),
  book("zephaniah", "Zephaniah", 3, "Софония", ["книга софонии", "софонии", "софония"], ["book of zephaniah", "zephaniah", "zeph"]),
  book("haggai", "Haggai", 2, "Аггей", ["книга аггея", "аггея", "аггей"], ["book of haggai", "haggai", "hag"]),
  book("zechariah", "Zechariah", 14, "Захария", ["книга захарии", "захарии", "захария"], ["book of zechariah", "zechariah", "zech"]),
  book("malachi", "Malachi", 4, "Малахия", ["книга малахии", "малахии", "малахия"], ["book of malachi", "malachi", "mal"], 4),
  book("matthew", "Matthew", 28, "От Матфея", ["евангелие от матфея", "евангелие от матвея", "от матфея", "от матвея", "матфея", "матфею", "матфей", "матвея", "матвею", "матвей", "матея"], ["gospel according to matthew", "gospel of matthew", "matthew", "mathew", "mattew"]),
  book("mark", "Mark", 16, "От Марка", ["евангелие от марка", "от марка", "марка", "марк"], ["gospel according to mark", "gospel of mark", "mark"]),
  book("luke", "Luke", 24, "От Луки", ["евангелие от луки", "от луки", "лукой", "луки", "лука"], ["gospel according to luke", "gospel of luke", "luke"]),
  book("john", "John", 21, "От Иоанна", ["евангелие от иоанна", "от иоанна", "иоанна", "иоанн"], ["gospel according to john", "gospel of john", "john"]),
  book("acts", "Acts", 28, "Деяния", ["деяния святых апостолов", "деяния апостолов", "деяний", "деяния"], ["acts of the apostles", "book of acts", "acts"]),
  book("romans", "Romans", 16, "К Римлянам", ["послание к римлянам", "к римлянам", "римлянам"], ["letter to the romans", "book of romans", "romans"]),
  book("1-corinthians", "1 Corinthians", 16, "1 Коринфянам", ["первое послание к коринфянам", "первое коринфянам", "первая коринфянам", "первые коринфянам", "первое коринфианом", "первое коринфианам", "1 коринфянам"], ["first corinthians", "1st corinthians", "1 corinthians"]),
  book("2-corinthians", "2 Corinthians", 13, "2 Коринфянам", ["второе послание к коринфянам", "второе коринфянам", "вторая коринфянам", "2 коринфянам"], ["second corinthians", "2nd corinthians", "2 corinthians"]),
  book("galatians", "Galatians", 6, "К Галатам", ["послание к галатам", "к галатам", "галатам"], ["letter to the galatians", "galatians", "gal"]),
  book("ephesians", "Ephesians", 6, "К Ефесянам", ["послание к ефесянам", "к ефесянам", "ефесянам"], ["letter to the ephesians", "ephesians", "eph"]),
  book("philippians", "Philippians", 4, "К Филиппийцам", ["послание к филиппийцам", "к филиппийцам", "филиппийцам"], ["letter to the philippians", "philippians", "phil"]),
  book("colossians", "Colossians", 4, "К Колоссянам", ["послание к колоссянам", "к колоссянам", "колоссянам"], ["letter to the colossians", "colossians", "col"]),
  book("1-thessalonians", "1 Thessalonians", 5, "1 Фессалоникийцам", ["первое послание к фессалоникийцам", "первое фессалоникийцам", "1 фессалоникийцам"], ["first thessalonians", "1st thessalonians", "1 thessalonians"]),
  book("2-thessalonians", "2 Thessalonians", 3, "2 Фессалоникийцам", ["второе послание к фессалоникийцам", "второе фессалоникийцам", "2 фессалоникийцам"], ["second thessalonians", "2nd thessalonians", "2 thessalonians"]),
  book("1-timothy", "1 Timothy", 6, "1 Тимофею", ["первое послание к тимофею", "первое тимофею", "1 тимофею"], ["first timothy", "1st timothy", "1 timothy"]),
  book("2-timothy", "2 Timothy", 4, "2 Тимофею", ["второе послание к тимофею", "второе тимофею", "2 тимофею"], ["second timothy", "2nd timothy", "2 timothy"]),
  book("titus", "Titus", 3, "К Титу", ["послание к титу", "к титу", "титу"], ["letter to titus", "titus"]),
  book("philemon", "Philemon", 1, "К Филимону", ["послание к филимону", "к филимону", "филимону"], ["letter to philemon", "philemon", "philem"], 1),
  book("hebrews", "Hebrews", 13, "К Евреям", ["послание к евреям", "к евреям", "евреям"], ["letter to the hebrews", "book of hebrews", "hebrews", "heb"]),
  book("james", "James", 5, "Иакова", ["послание иакова", "иакова", "иаков"], ["letter of james", "book of james", "james"]),
  book("1-peter", "1 Peter", 5, "1 Петра", ["первое послание петра", "первое петра", "1 петра"], ["first peter", "1st peter", "1 peter"]),
  book("2-peter", "2 Peter", 3, "2 Петра", ["второе послание петра", "второе петра", "2 петра"], ["second peter", "2nd peter", "2 peter"]),
  book("1-john", "1 John", 5, "1 Иоанна", ["первое послание иоанна", "первое иоанна", "1 иоанна"], ["first john", "1st john", "1 john"]),
  book("2-john", "2 John", 1, "2 Иоанна", ["второе послание иоанна", "второе иоанна", "2 иоанна"], ["second john", "2nd john", "2 john"], 1),
  book("3-john", "3 John", 1, "3 Иоанна", ["третье послание иоанна", "третье иоанна", "3 иоанна"], ["third john", "3rd john", "3 john"], 1),
  book("jude", "Jude", 1, "Иуды", ["послание иуды", "иуды", "иуда"], ["letter of jude", "book of jude", "jude"], 1),
  book("revelation", "Revelation", 22, "Откровение", ["откровение иоанна богослова", "откровение иоанна", "апокалипсис", "откровения", "откровение"], ["revelation of john", "book of revelation", "revelations", "revelation"]),
];
